---
- name: install pkgs...
  package: name={{item}} state=present
  with_items:
    - maven
    - ant

- name: (Debian) install...
  when: ansible_os_family == 'Debian'
  include: Debian.yml

- name: (RedHat) install...
  when: ansible_os_family == 'RedHat'
  include: RedHat.yml
