---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"
    
- name: install pkgs...
  become: yes
  become_user: root
  package: name={{item}} state=present
  with_items:
    - maven
    - ant

- name : configurate maven...
  become: yes
  become_user: root
  with_items:
    - settings.xml
    - toolchains.xml
    - m2.conf
  template: >
    dest={{java_build_tools_maven_settings_dir}}/{{item}}
    src=usr/share/maven/conf/{{item}}.j2
    mode=0644
